### PR TITLE
Update for Catalina

### PR DESCRIPTION
**Pull request by conorhalloran**
## Description:
Update the present laptop script to be compatible with Mac OS Catalina. Update the applications installed via the script and creates a laptop file which can be used in the future to easily expand the capabilities of this install script. 

This is **[dependant on the dotfiles PR](https://github.com/sprk/spark-tools/pull/2)** getting merged as it pulls from that repository to automatically setup those dotfiles.
1. The $PATH is invoked within the .zshenv as export PATH="$HOME/.rbenv/bin:$PATH" then sourced in the .zshrc
2. This was needed to ensure rbenv was invoked in all instances of the shell  [(Catalina issue)](https://programmingzen.com/installing-rbenv-on-zsh-on-macos/).

I wasn't able to get this to successfully install the rbenv ruby version without breaking the script. Instructions for how to do that, after the script is run, is listed in the README.md.

### CODE REVIEW

**Comment by ryanilg** [comment]
This is still in my court. I am planning on setting up a new machine with this when I get a chance, so I can actually provide "real" feedback. Stay tuned!

**Comment by conorhalloran** [comment]
Cool! Interested to hear your thoughts on `rbenv` vs `chruby` Given rbenv's headache with Catalina + script break as a means to complete install, could be worth a transition look?

**Comment by ryanilg** [comment]
Personally I'd prefer to stick with `rbenv` and `ruby-build` given we also use them on the servers. I would hate to fall into the trap of "we implemented something else because at the time nothing else worked" and then later switch back to rbenv when it's working correctly, (and we know support will be fixed in the future), as we would then have different systems with different implementations, which can make diagnostics a nightmare.

**Comment by conorhalloran** [comment]
> .re!

lol, doh! Shows how much I use our email address' :D

**Review by ryanilg — APPROVED** [review]
LGTM!

**Pull request merged**
